### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by tfausak**

### CODE REVIEW

**Comment by NorfairKing** [comment]
I'm subscribing myself here because I want to see how you'll do parsing.

**Comment by NorfairKing** [comment]
> This is aiming for the typical flow of parsing bytes into JSON, and then converting that JSON into regular Haskell types.

Yeah that's alright!

> I am curious about one aspect of the codec approach: Since parsers are applicative, how do you handle tagged constructors? For example Either Bool Int is normally encoded as something like { "tag": "Left", "val": false }. With a monadic parser it's pretty easy to grab the "tag" and then choose what to do based on that.

1. I could also offer monadic parsing, but without the auto-documentation
2. You can actually still do applicative parsing in that case. Something like this (pseudocode): `(Left <$ literalField "tag" "Left" <$> field "val" ) <|> (Right <$ literalField "tag" "Right" <$> field "val")`. That's how I do it in `yamlparse-applicative`:  https://hackage.haskell.org/package/yamlparse-applicative

**Comment by NorfairKing** [comment]
> This PR has basic decoding implemented as of fdf10a2. I think it's mostly alright, but I'm not happy with how it deals with escaped characters. Going through String is not ideal, but properly handling surrogate pairs is a pain.

I can recommend making tests like I did here (I didn't get them to pass): 
https://github.com/NorfairKing/json-codec/blob/4ffc5ef8e236e7ae4ee7c7398df235f203e9f333/test/JSON/CodecSpec.hs

**Comment by tfausak** [comment]
I'm going to merge this PR and cut an initial release. Then I'm going to (probably slowly) develop the features I listed above. If you're interested in following along, there will be more PRs in the coming days and weeks.

**Pull request merged**
